### ISSUE TITLE
Install error about activate_this.py

### ISSUE THREAD

**Issue by sda910722** [cfce/chilin#9]
Hi everyone,

To install chilin, I followed all of the instruction in https://github.com/cfce/chilin
But I got this error
```
[sda@admin chilin]$ python setup.py install -f
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 22, in <module>
    import io
  File "/pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodec_LookupTextEncoding
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/site-packages/pkg_resources/__init__.py", line 22, in <module>
    import io
  File "/pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/io.py", line 51, in <module>
    import _io
ImportError: /pub5/xiaoyun/BioSoftware/Python-2.7.12/lib/python2.7/lib-dynload/_io.so: undefined symbol: _PyCodec_LookupTextEncoding
Traceback (most recent call last):
  File "setup.py", line 315, in <module>
    main()
  File "setup.py", line 310, in main
    install_full()
  File "setup.py", line 217, in install_full
    execfile("chilin_env/bin/activate_this.py", dict(__file__="chilin_env/bin/activate_this.py"))
IOError: [Errno 2] No such file or directory: 'chilin_env/bin/activate_this.py'

```
I have checked this file, "chilin_env/bin/activate_this.py" in github, it is indeed not exists.
Is it generated by setup.py? What should I do?

**Comment by sda910722** [comment]
This error could be fiexed by installing  virtualenv package using pip ...

pip install virtualenv

**Comment by qinqian** [comment]
Thanks for the point, we'll update this information.
